# Generated by Django 5.2.2 on 2025-06-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SitioTuristico',
            new_name='Sitio',
        ),
    ]
