# Generated by Django 5.2.2 on 2025-06-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0002_rename_sitioturistico_sitio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParadaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('onestop_id', models.CharField(max_length=100, unique=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='lugares.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='RutaSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_min', models.IntegerField()),
                ('distancia_metros', models.IntegerField()),
                ('parada_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.paradatransporte')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.sitio')),
            ],
        ),
    ]
