# Generated by Django 5.2.2 on 2025-06-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0003_paradatransporte_reseña_rutasitio'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('horarios', models.CharField(max_length=255)),
                ('costo', models.CharField(max_length=100)),
                ('imagen', models.URLField()),
            ],
        ),
    ]
