# Generated by Django 5.2.2 on 2025-06-17 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lugares', '0004_lugarturistico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseña',
            name='sitio',
        ),
        migrations.AddField(
            model_name='reseña',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reseña',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
